name: VitalKeepExp
version: @version@
main: dev.meinel.leo.vitalkeepexp.VitalKeepExp
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to keep exp on death.
permissions:
  vitalkeepexp.keep:
    description: "Permission to keep exp on death"
    default: op